### ISSUE TITLE
[FE] 프론트 빌드 에러 임시 수정

### ISSUE THREAD

**Issue by kookyungmin** [EveryBuddyMoney/PetBuddy#15]
- [x] 망할 댄싱 컴포넌트 타입 맞추기

![image](https://user-images.githubusercontent.com/26543603/211248877-f4ea4dd2-4970-4801-88d4-041dc47cd29d.png)

![image](https://user-images.githubusercontent.com/26543603/211248896-bcb985b2-de48-4b9e-bd2e-16df31e9f5e2.png)

![image](https://user-images.githubusercontent.com/26543603/211248908-f21c66dd-4252-4eb4-9772-e9353db22596.png)

**Comment by kookyungmin** [comment]
@kdw1521 리팩토링 무조건 꼭 하세요 컴포넌트 모듈화 + 네이밍 신경써주세요~!

**Comment by kdw1521** [comment]
> @kdw1521 리팩토링 무조건 꼭 하세요 컴포넌트 모듈화 + 네이밍 신경써주세요~!

@kookyungmin ㅋㅋㅋㅋ 고생하셨습니다. 감자합니다
